version: "3.2"

services:
    front:
        environment:
          - VIRTUAL_HOST=${CI_HOST}
          - VIRTUAL_PORT=80

networks:
    frontend:
        external:
            name: nginxproxy_default
